# GCP e2-small + k3s values
replicaCount: 2

service:
  type: ClusterIP

ingress:
  enabled: true
  host: "" # set to your nip.io or custom domain, e.g. flash.<YOUR_IP>.nip.io
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
