apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-decks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
{{- $root := . }}
{{- range $path, $_ := .Files.Glob "decks/*.json" }}
  {{ base $path }}: |
{{ $root.Files.Get $path | indent 4 }}
{{- end }}
